title: Carl Rippon
description: The economics of disasters in small, open island economies.
url: "https://carlrippon.github.io"
lang: en

# Les billets de blog seront publiés sous /blog/titre-du-billet/
permalink: /blog/:title/
